spring:
  springdoc:
    version: 3.0

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:~/tweet-client;MODE=MySQL
    username: sa
    password: 1234


twitter4j:
  oauth:
    key: Yf3KAa1ABZS55wavW7xfNNu4q
    secret-key: CwE4HfIVxN3NyVwWZqfiN9SXQDrMmwJvrGJTEYoqYhjdpH1Zo2
    access-token: 939234766402084864-BGqitGAGiPBrxmb7JB03HfMF3ROVn6g
    access-token-secret: oNyS5inQGLykvPvGQrchqeqEBHPxQ3zbHGST8k0Frunir

