spring:
  springdoc:
    version: 3.0

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:~/tweet-client;MODE=MySQL
    username: sa
    password: 1234




